version: '3.6'

services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjsapitutorial

  test_database:
    image: postgres:latest
    container_name: postgres_test
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjsapitutorial_test
